trigger: none

pool:
  vmImage: ubuntu-latest

stages:
  - stage: deployManifests
    jobs:
      - job: deployJob
        steps:
        - task: KubectlInstaller@0
          inputs:
            kubectlVersion: 'latest'

        - task: KubernetesManifest@1
          inputs:
            action: 'deploy'
            connectionType: 'kubernetesServiceConnection'
            kubernetesServiceConnection: 'k8s'
            namespace: 'myspace'
            manifests: |
                manifests/deployment.yaml
                manifests/service.yaml
