apiVersion: v1
kind: Service
metadata:
  name: myapp-service
  namespace: myspace
  labels:
    svc: myapp-service
spec:
  selector:
    app: my-app
  ports:
  - port: 80
    targetPort: 80
    name: http
  type: LoadBalancer



