apiVersion: v1
kind: Service
metadata:
  name: myapp-service
  labels:
    app: my-app
spec:
  selector:
    app: my-app
  ports:
  - port: 80
    targetPort: 80
    name: http
  type: LoadBalancer



